<h1><?php echo $this->iconMgr("PROFILE") ?><?php echo $this->formTitle; ?></h1>

<?php $this->form->setAction($this->url()) ?>
<?php echo $this->form ?>
<script>
    function view_resources() {
            this.document.location.href = "<?php
            echo $this->baseUrl()."/webmanage/accessprofile/viewresources/name/";
            ?>" + document.forms["access_profile"]["name"].value
    }
</script>
<center>
<form id="view_resource">
    <input type="button" onclick="view_resources();" value="Mostrar recursos"/>
</form>
</center>
<p/>
<div class="actions">
    <ul>
        <li><?php echo $this->iconMgr("BACK") ?>
            <a href="<?php echo $this->baseUrl()."/webmanage/accessprofile"; ?>">
                Volver al listado
            </a>
        </li>
    </ul>
</div>
