#!/bin/bash


IPT=/sbin/iptables
VPN_NETWORK=<?php echo $this->_gwConf->getVpnNetwork(); ?> 
OVPN_PORT=1194

### Tunning del kernel
# habilito forwarding de paquetes
echo 1 > /proc/sys/net/ipv4/ip_forward

# protección anti spoofing del kernel
echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter


### Limpieza de reglas
# limpio todas las reglas
$IPT -F
$IPT -t nat -F
$IPT -t mangle -F

# eliminto las cadenas definidas por el usuario
$IPT -X
$IPT -t nat -X
$IPT -t mangle -X

# pongo a cero contadores
$IPT -Z

### Políticas globales
$IPT -P INPUT DROP
$IPT -P FORWARD DROP
$IPT -P OUTPUT ACCEPT


### Filtrado de entrada
# acepto todo el tráfico de loopback
$IPT -A INPUT -i lo -j ACCEPT

# acepto tráfico ICMP
$IPT -A INPUT -p icmp -j ACCEPT

# acepto tráfico ssh
$IPT -A INPUT -p tcp --dport 22 -j ACCEPT

# acepto tráfico openvpn
$IPT -A INPUT -p udp --dport $OVPN_PORT -j ACCEPT


# acepto conexiones entrantes relacionadas
$IPT -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT


### Creación de cadenas de usuario para los perfiles de acceso
<?php foreach ($this->_profiles as $profile): ?>
$IPT -N Profile_<?php echo $profile->getName(); ?> 
    <?php foreach ($profile->getResources() as $resource) :?>
$IPT -A Profile_<?php echo $profile->getName(); ?> <?php echo $this->_getIptParams($resource); ?> -j ACCEPT
    <?php endforeach; ?>
<?php endforeach; ?>

### Filtrado de forwarding
# permito si se trata de una conexión establecida
$IPT -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# reglas individuales por ip a cadena de usuario oportuna
<?php foreach ($this->_clients as $client): ?>
# regla de <?php echo $client->getName(); ?> 
    <?php if($client->isIptablesLogged()): ?>
$IPT -A FORWARD -s <?php echo $client->getVpnIp(); ?> -j LOG 
    <?php endif; ?>
$IPT -A FORWARD -s <?php echo $client->getVpnIp(); ?> -j Profile_<?php echo $client->getProfile()->getName(); ?> 
<?php endforeach; ?>

# antes de descartar logeo por si viene de vpn para localizar intentos frustrados
$IPT -A FORWARD -s $VPN_NETWORK -j LOG
